version: 2
updates:
  # Maintain Python dependencies in /python
  - package-ecosystem: "pip"
    directory: "/python"
    schedule:
      interval: "weekly"

  # Maintain Node.js dependencies in /node
  - package-ecosystem: "npm"
    directory: "/node"
    schedule:
      interval: "weekly"

  # Maintain GitHub Actions in CI/CD workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
