# FILE: tests/test_repro_para_id_signed_int32.py
"""
Repro tests for BUG_paraId_signed_int32_thread_collapse.md (B5, 2026-08-12,
Adeu 2.2.0 / 0db3cc2) — the CI half. The Word-verified half lives in
tests/test_live_word_para_id_signed_int32.py and needs Windows + Word.

`_generate_para_id` and `_generate_rsid` drew from `0 .. 0xFFFFFFFF`. Word
parses every `ST_LongHexNumber` as a SIGNED 32-bit integer and ECMA-376
requires the value to be greater than `0x00000000` and less than `0x80000000`,
so roughly HALF of every paraId Adeu minted was thrown away and regenerated by
Word on load — dangling every `w15:paraIdParent` that pointed at it and
dropping the reply out of its thread.

This is the third occurrence of one root cause:

    2026-08-11 B3   w16cid:durableId   comment anchor collapses to a point
    2026-08-12 B5   w14:paraId         reply threading collapses
    2026-08-12 B5   w:rsid*            no observed symptom; masked anyway

B3 was fixed as a POINT FIX to one attribute, and the reasoning behind it
("paraId and rsid are opaque 32-bit tokens with no such constraint") was
recorded as settled fact in two docstrings, AI_CONTEXT.md, and two tests that
went red when the bug was fixed. The point of this file is that it does not
care which attribute is the special one: `test_saved_package_carries_no_out_of
_range_long_hex_numbers` scans EVERY ST_LongHexNumber in the saved package, and
would have caught all three instances on the day they shipped.

Test-first: every assertion here fails on the pre-fix engine.
"""

import io
import random
import re
import zipfile
from typing import Dict, Optional

import pytest
from docx import Document

from adeu.models import ModifyText, ReplyComment
from adeu.redline.comments import CommentsManager
from adeu.redline.engine import RedlineEngine
from adeu.utils.long_hex_number import (
    ST_LONG_HEX_NUMBER_MAX,
    ST_LONG_HEX_NUMBER_MIN,
    is_word_readable_long_hex_number,
    to_long_hex_number,
)
from tests.utils import (
    assert_word_readable_ids,
    edge_of_range_randint,
    find_duplicate_para_ids,
    find_out_of_range_long_hex_numbers,
    find_text_ids_without_para_id,
)

#: Word's rule for every ST_LongHexNumber, from ECMA-376: "shall be greater
#: than 0x00000000 and less than 0x80000000". Restated here as LITERALS on
#: purpose: the engine and the package scanner both derive their bounds from
#: adeu.utils.long_hex_number, so a wrong constant there would agree with
#: itself and pass. TestTheRuleItself is what stops that.
LEGAL_MIN = 0x00000001
LEGAL_MAX = 0x7FFFFFFF

#: 256 samples: a generator drawing from the full 32-bit range fails a
#: high-bit assertion with probability 1 - 2^-256, i.e. deterministically.
SAMPLES = 256

BODY = "The parties shall confer in good faith before moving to compel production."
TARGET = "confer in good faith"


def doc_stream(*paragraphs: str) -> io.BytesIO:
    doc = Document()
    for text in paragraphs or (BODY,):
        doc.add_paragraph(text)
    buf = io.BytesIO()
    doc.save(buf)
    buf.seek(0)
    return buf


def manager() -> CommentsManager:
    return CommentsManager(Document())


def threaded_package(reply_count: int = 2) -> bytes:
    """A saved package with one comment thread carrying `reply_count` replies."""
    engine = RedlineEngine(doc_stream(), author="Sarah Chen")
    engine.apply_edits([ModifyText(target_text=TARGET, new_text=TARGET, comment="Root note.")])
    root_id = next(iter(engine.comments_manager.extract_comments_data()))
    engine.author = "Adeu AI"
    for i in range(reply_count):
        engine.apply_review_actions([ReplyComment(target_id=f"Com:{root_id}", text=f"Reply {i}.")])
    return engine.save_to_stream().getvalue()


# ---------------------------------------------------------------------------
# Inherited ids (B6) — building a package Adeu did not mint
# ---------------------------------------------------------------------------
#
# B5 masked every id Adeu MINTS. B6 is the other half: an id Adeu READS from
# the document it was handed. The engine cannot mint its way out of that one —
# it has to repair what it inherited, which is what these helpers set up.

#: The value the western-district demo actually shipped with (2026-08-12): a
#: perfectly ordinary paraId whose top bit happens to be set.
POISON = "D2AEAE20"

#: What folding POISON into range produces. Word-verified: patching the demo
#: document's root paraId to exactly this value made the reply thread.
POISON_FOLDED = "52AEAE20"


def repack(package: bytes, rewrite) -> bytes:
    """Rebuild a DOCX with `rewrite` applied to the text of every XML part."""
    out = io.BytesIO()
    with zipfile.ZipFile(io.BytesIO(package)) as src:
        with zipfile.ZipFile(out, "w", zipfile.ZIP_DEFLATED) as dst:
            for item in src.infolist():
                data = src.read(item.filename)
                if item.filename.endswith(".xml"):
                    data = rewrite(item.filename, data.decode("utf-8")).encode("utf-8")
                dst.writestr(item, data)
    return out.getvalue()


def poison(package: bytes, replacements: Dict[str, str]) -> bytes:
    """Rewrite ST_LongHexNumber values across every part, references included.

    This is exactly what produced the demo document: a fixture builder that
    rewrote the ids in a Word-authored package, masked `w16cid:durableId`
    because B3 had taught it to, and left `w14:paraId` alone because the note
    B3 left behind said paraId was unconstrained. The result validates against
    the schema, opens without complaint, and silently loses its thread.
    """

    def rewrite(_name: str, text: str) -> str:
        for old, new in replacements.items():
            text = text.replace(f'"{old}"', f'"{new}"')
        return text

    return repack(package, rewrite)


def part_text(package: bytes, stem: str) -> str:
    """The text of `word/<stem>.xml`, tolerating python-docx's part numbering.

    Word writes `word/comments.xml`; python-docx writes `word/comments1.xml`
    for the same part. Matching the stem exactly (rather than by substring)
    also keeps `comments` from selecting `commentsExtended`.
    """
    pattern = re.compile(rf"^word/{stem}\d*\.xml$")
    with zipfile.ZipFile(io.BytesIO(package)) as archive:
        name = next((n for n in archive.namelist() if pattern.match(n)), None)
        assert name, f"no word/{stem}.xml part in {archive.namelist()}"
        return archive.read(name).decode("utf-8")


def comment_ex_entries(package: bytes):
    """`[(paraId, paraIdParent or None)]` from commentsExtended, in order."""
    xml = part_text(package, "commentsExtended")
    return [
        (m.group("id"), m.group("parent"))
        for m in re.finditer(
            r'<w15:commentEx\b(?=[^>]*\bw15:paraId="(?P<id>[0-9A-Fa-f]{1,8})")'
            r'(?=(?:[^>]*\bw15:paraIdParent="(?P<parent>[0-9A-Fa-f]{1,8})")?)[^>]*>',
            xml,
        )
    ]


def root_para_id(package: bytes) -> str:
    """The one commentEx with no parent — the thread root."""
    roots = [para_id for para_id, parent in comment_ex_entries(package) if not parent]
    assert len(roots) == 1, f"fixture precondition: expected exactly one thread root, got {roots}"
    return roots[0]


def thread_of(package: bytes) -> Dict[str, Optional[str]]:
    return dict(comment_ex_entries(package))


def para_ids_in(package: bytes, part: str = "comments"):
    return re.findall(r'w14:paraId="([0-9A-Fa-f]{1,8})"', part_text(package, part))


def reply_to_root(package: bytes, text: str = "Addressed.", author: str = "Adeu AI") -> bytes:
    """Reply to whichever comment owns the thread root, and save."""
    engine = RedlineEngine(io.BytesIO(package), author=author)
    comments = engine.comments_manager.extract_comments_data()
    applied, skipped, _ = engine.apply_review_actions(
        [ReplyComment(target_id=f"Com:{next(iter(comments))}", text=text)]
    )
    assert (applied, skipped) == (1, 0), "the reply did not apply at all"
    return engine.save_to_stream().getvalue()


def offenders(values, label: str) -> str:
    bad = [v for v in values if not LEGAL_MIN <= int(v, 16) <= LEGAL_MAX]
    return (
        f"{len(bad)}/{len(values)} generated {label}s are outside "
        f"(0x00000000, 0x80000000) — e.g. {bad[:4]}. Word parses ST_LongHexNumber as a SIGNED "
        "32-bit integer: it discards these on load and regenerates them, breaking every "
        "reference that pointed at them."
    )


# ---------------------------------------------------------------------------
# The rule itself
# ---------------------------------------------------------------------------


class TestTheRuleItself:
    """
    `adeu.utils.long_hex_number` is the single definition of "an id Word will
    keep": the generators mint against it and the package scanner audits
    against it. That is the right structure, and it has one failure mode — a
    wrong constant would be consistent with itself everywhere. Everything here
    checks it against LITERALS taken from the spec text, not against itself.
    """

    def test_the_bounds_are_the_ones_ecma_376_states(self):
        assert (ST_LONG_HEX_NUMBER_MIN, ST_LONG_HEX_NUMBER_MAX) == (LEGAL_MIN, LEGAL_MAX), (
            "ECMA-376: the value shall be greater than 0x00000000 and less than 0x80000000"
        )

    @pytest.mark.parametrize(
        "value, readable, why",
        [
            ("00000000", False, "forbidden: Word rejects the whole package"),
            ("00000001", True, "smallest legal value"),
            ("12345678", True, "ordinary value"),
            ("7FFFFFFF", True, "largest legal value"),
            ("80000000", False, "smallest illegal value — exactly one greater"),
            ("D2AEAE20", False, "the id from the field report that collapsed the thread"),
            ("FFFFFFFF", False, "all bits set"),
            ("", False, "not a value at all"),
            ("1234567", True, "short forms are legal; Word writes them padded"),
            ("123456789", False, "too long for xsd:hexBinary length 4"),
            ("ZZZZZZZZ", False, "not hexadecimal"),
        ],
    )
    def test_the_predicate_agrees_with_the_specification(self, value, readable, why):
        assert is_word_readable_long_hex_number(value) is readable, why

    @pytest.mark.parametrize(
        "value, folded",
        [
            (0x00000000, "00000001"),  # 0 is forbidden, so it cannot be the identity
            (0x00000001, "00000001"),
            (0x7FFFFFFF, "7FFFFFFF"),
            (0x80000000, "00000001"),  # masks to 0, which is forbidden -> MIN
            (0x80000001, "00000001"),
            (0xFFFFFFFF, "7FFFFFFF"),
            (0xFC855CFC, "7C855CFC"),  # the first id Node's cell anchor derived
        ],
    )
    def test_folding_a_derived_value_lands_in_range(self, value, folded):
        """`to_long_hex_number` is for ids that are DERIVED rather than drawn —
        Node's `{#cell:paraId}` FNV fallback is the caller. Clearing the high
        bit is what Word effectively does anyway."""
        assert to_long_hex_number(value) == folded
        assert is_word_readable_long_hex_number(to_long_hex_number(value))


# ---------------------------------------------------------------------------
# The generators
# ---------------------------------------------------------------------------


class TestGeneratorRanges:
    """
    Every `ST_LongHexNumber` Adeu mints must land in `(0x00000000,
    0x80000000)`. Parametrised over all three generators deliberately: the way
    this bug shipped was a fix applied to exactly one of them, so a per-
    attribute test is how the class survives.
    """

    @pytest.mark.parametrize("generator", ["_generate_para_id", "_generate_rsid", "_generate_durable_id"])
    def test_generated_ids_are_valid_st_long_hex_numbers(self, generator):
        mint = getattr(manager(), generator)
        values = [mint() for _ in range(SAMPLES)]
        assert all(LEGAL_MIN <= int(v, 16) <= LEGAL_MAX for v in values), offenders(
            values, generator.removeprefix("_generate_")
        )

    @pytest.mark.parametrize("generator", ["_generate_para_id", "_generate_rsid", "_generate_durable_id"])
    def test_generated_ids_are_eight_upper_case_hex_digits(self, generator):
        mint = getattr(manager(), generator)
        for _ in range(64):
            value = mint()
            assert re.fullmatch(r"[0-9A-F]{8}", value), (
                f"{generator} produced {value!r}, which is not an 8-digit upper-case ST_LongHexNumber"
            )

    @pytest.mark.parametrize("generator", ["_generate_para_id", "_generate_rsid", "_generate_durable_id"])
    def test_no_generator_can_return_zero(self, generator, monkeypatch):
        """
        `00000000` is forbidden as explicitly as the high half, and it is the
        one value in this class Word does NOT paper over: a comment paragraph
        with `w14:paraId="00000000"` makes Word declare the file corrupted and
        refuse to open it (Word-verified). `randint(0, …)` can return it.
        """
        # The smallest value this generator can possibly emit.
        monkeypatch.setattr(random, "randint", lambda a, b: a)
        assert getattr(manager(), generator)() != "00000000", (
            f"{generator} can mint 00000000. Word rejects the whole package: the generator must start at 1, not 0."
        )

    def test_every_generator_draws_from_the_same_range(self, monkeypatch):
        """
        The class-level guard. B3 was fixed by giving ONE attribute its own
        masked generator and writing down that the others did not need it —
        which is precisely how B5 shipped. Pinning that the generators agree
        makes 'narrow one, leave the others' fail at the next attempt.
        """
        names = ("_generate_para_id", "_generate_rsid", "_generate_durable_id")
        for edge, expected in ((lambda a, b: a, "00000001"), (lambda a, b: b, "7FFFFFFF")):
            monkeypatch.setattr(random, "randint", edge)
            mgr = manager()
            bounds = {name: getattr(mgr, name)() for name in names}
            assert set(bounds.values()) == {expected}, (
                f"the generators do not share a bound: {bounds}. Every ST_LongHexNumber goes "
                "through one generator; there is no attribute for which the high half is safe."
            )


# ---------------------------------------------------------------------------
# The general guard — what would have caught all three instances
# ---------------------------------------------------------------------------


class TestSavedPackageIds:
    def test_saved_package_carries_no_out_of_range_long_hex_numbers(self):
        """
        Attribute-agnostic, end-to-end: scan every `.xml` part of a saved
        package for every attribute typed `ST_LongHexNumber` and require all of
        them to be in range. Prefer this to three attribute-specific tests — it
        is what turns a third point fix into a closed class.
        """
        assert_word_readable_ids(threaded_package(), context="threaded document: ")

    @pytest.mark.parametrize("high", [True, False], ids=["top-of-range", "bottom-of-range"])
    def test_no_call_site_can_reach_an_unmasked_generator(self, high, monkeypatch):
        """
        `random.randint` is pinned to one END of whatever range each generator
        asks for — always a value that call could legitimately have returned.
        A generator over `0 .. 0xFFFFFFFF` then mints `FFFFFFFF…` (high) or
        `00000000…` (low); a masked one mints `7FFFFFFF…` / `00000001…`.

        Because the substitution is global, this covers every mint site that
        `add_comment` can reach — not just the ones a reviewer remembered — and
        it fails deterministically rather than 50% of the time.
        """
        monkeypatch.setattr(random, "randint", edge_of_range_randint(high=high))
        assert_word_readable_ids(threaded_package(reply_count=3), context=f"{'high' if high else 'low'} RNG: ")

    @pytest.mark.parametrize(
        "attribute",
        ["w14:paraId", "w14:textId", "w15:paraIdParent", "w16cid:durableId", "w:rsidR", "w:rsidSect"],
    )
    @pytest.mark.parametrize("value", ["80000000", "FFFFFFFF", "00000000"])
    def test_the_package_scanner_detects_every_shape_of_bad_id(self, attribute, value):
        """
        Guards the guard. A scanner that silently matched nothing would make
        every test above vacuous, and a bug class that hides behind a check
        which never fires is exactly what this file exists to stop. Built from
        a synthetic package so it measures the SCANNER, not the engine.
        """
        package = self._synthetic_package(f'<w:p {attribute}="{value}"/>')
        assert [(attr, val) for _part, attr, val in find_out_of_range_long_hex_numbers(package)] == [(attribute, value)]

    @pytest.mark.parametrize("value", ["00000001", "7FFFFFFF", "12345678"])
    def test_the_package_scanner_accepts_legal_ids(self, value):
        package = self._synthetic_package(f'<w:p w14:paraId="{value}"/>')
        assert find_out_of_range_long_hex_numbers(package) == []

    def test_the_package_scanner_reads_the_w_rsids_element_form(self):
        """`<w:rsid w:val="…"/>` in settings.xml carries the same type in an
        element rather than on the paragraph. Adeu does not write it today;
        the scanner covers it so that the day something does, it is checked."""
        package = self._synthetic_package('<w:rsids><w:rsidRoot w:val="C0000001"/></w:rsids>')
        assert [attr for _part, attr, _v in find_out_of_range_long_hex_numbers(package)] == ["w:rsidRoot/@w:val"]

    @staticmethod
    def _synthetic_package(fragment: str) -> bytes:
        import zipfile

        buffer = io.BytesIO()
        with zipfile.ZipFile(buffer, "w") as archive:
            archive.writestr("word/document.xml", f"<w:document>{fragment}</w:document>")
            # Non-XML parts must be skipped, not decoded as text.
            archive.writestr("word/media/image1.png", b"\x89PNG\r\n\x1a\n\xff\xff\xff\xff")
        return buffer.getvalue()

    def test_a_document_with_no_comments_is_already_clean(self):
        """
        Baseline: the ids Adeu inherits from python-docx's template (rsids in
        settings/styles, the body paragraph ids) are all in range, so a failure
        of the scan above can only be something Adeu minted.
        """
        engine = RedlineEngine(doc_stream(), author="Adeu AI")
        engine.apply_edits([ModifyText(target_text="good faith", new_text="good faith and candor")])
        assert_word_readable_ids(engine.save_to_stream().getvalue(), context="no comments: ")


# ---------------------------------------------------------------------------
# Threading: the consumer-visible symptom
# ---------------------------------------------------------------------------


class TestThreadingIdsResolve:
    W15 = "http://schemas.microsoft.com/office/word/2012/wordml"

    @staticmethod
    def _comment_ex(package: bytes):
        import zipfile

        with zipfile.ZipFile(io.BytesIO(package)) as archive:
            name = next(n for n in archive.namelist() if "commentsExtended" in n)
            xml = archive.read(name).decode("utf-8")
        return re.findall(r'w15:paraId="([0-9A-Fa-f]{8})"(?:\s+w15:paraIdParent="([0-9A-Fa-f]{8})")?', xml)

    def test_every_reply_points_at_an_in_range_parent_para_id(self):
        """
        64 independent threads, so a generator that is right half the time
        cannot pass by luck (2^-64). B1 already guarantees a reply carries
        `w15:paraIdParent`; what this adds is that the value it points AT is
        one Word will still recognise after load. A reply can be perfectly
        parented in the XML and still not thread.
        """
        dangling = []
        for _ in range(64):
            entries = self._comment_ex(threaded_package(reply_count=1))
            roots = {para_id for para_id, parent in entries if not parent}
            for para_id, parent in entries:
                if not parent:
                    continue
                assert parent in roots, f"reply {para_id} points at unknown parent {parent}"
                if not LEGAL_MIN <= int(parent, 16) <= LEGAL_MAX:
                    dangling.append(parent)
                if not LEGAL_MIN <= int(para_id, 16) <= LEGAL_MAX:
                    dangling.append(para_id)

        assert not dangling, (
            f"{len(dangling)}/64 threads reference a paraId Word will discard: {dangling[:4]}. "
            "The reply IS parented — process_batch reports success and B1's CommentThreadingError "
            "correctly does not fire — it just stops being a reply the moment Word opens the file."
        )

    def test_a_legacy_parent_adopted_for_threading_gets_an_in_range_para_id(self, monkeypatch):
        """
        The second mint site: a parent comment with no `w14:paraId` (pre-2013
        Word, or any generator without the modern-comments extensions) has one
        minted for it so the reply can thread (`_adopt_into_modern_comments`).
        That id is the thread ROOT, the worst place for a bad one — an
        out-of-range root takes every reply in the thread down with it.
        """
        engine = RedlineEngine(doc_stream(), author="Sarah Chen")
        engine.apply_edits([ModifyText(target_text=TARGET, new_text=TARGET, comment="Legacy note.")])
        source = engine.save_to_stream()

        # Strip the paraId to produce the legacy comment shape.
        from docx.oxml.ns import qn

        source.seek(0)
        doc = Document(io.BytesIO(source.getvalue()))
        comments_part = next(
            p for p in doc.part.package.parts if p.content_type.endswith("wordprocessingml.comments+xml")
        )
        from docx.opc.part import XmlPart
        from docx.oxml import parse_xml

        element = parse_xml(comments_part.blob)
        stripped = 0
        for comment in element.findall(qn("w:comment")):
            for para in comment.findall(qn("w:p")):
                if para.get(qn("w14:paraId")) is not None:
                    del para.attrib[qn("w14:paraId")]
                    stripped += 1
        assert stripped, "fixture precondition: nothing to strip"

        replacement = XmlPart(comments_part.partname, comments_part.content_type, element, comments_part.package)
        package = comments_part.package
        package.parts[package.parts.index(comments_part)] = replacement
        for rel in doc.part.rels.values():
            if not rel.is_external and rel.target_part is comments_part:
                rel._target = replacement
        legacy = io.BytesIO()
        doc.save(legacy)
        legacy.seek(0)

        monkeypatch.setattr(random, "randint", edge_of_range_randint(high=True))
        engine = RedlineEngine(legacy, author="Adeu AI")
        parent_id = next(iter(engine.comments_manager.extract_comments_data()))
        applied, skipped, _ = engine.apply_review_actions(
            [ReplyComment(target_id=f"Com:{parent_id}", text="Addressed.")]
        )
        assert (applied, skipped) == (1, 0), "the reply did not apply at all"

        assert_word_readable_ids(engine.save_to_stream().getvalue(), context="adopted legacy parent: ")


# ---------------------------------------------------------------------------
# B6: the id Adeu did not mint
# ---------------------------------------------------------------------------


class TestAnInheritedOutOfRangeIdIsRepaired:
    """
    B6 (2026-08-12, western-district demo). B5 fixed every id Adeu MINTS, and
    the two tests above prove it: both build their parent with the fixed
    engine, so the thread root is always already legal. Neither covers a parent
    that arrives with an id Word will throw away.

    That is the case that shipped. Sarah Chen's comment came in carrying
    `w14:paraId="D2AEAE20"`, `_adopt_into_modern_comments` found a paraId and
    reused it verbatim, and the reply's `w15:paraIdParent` was written to point
    at a value Word discards on load. Every check passed on the way out — the
    reply IS parented, `CommentThreadingError` correctly did not fire, and the
    package scanner was only ever run against ids the engine minted.

    Adeu cannot mint its way out of an inherited id. It has to repair it, and
    repair it everywhere it is referenced, or the repair de-threads the replies
    that were already pointing at it.
    """

    def test_a_reply_threads_onto_a_parent_whose_para_id_word_would_discard(self):
        """The demo, reduced: one inherited high-bit paraId, one reply."""
        base = threaded_package(reply_count=0)
        package = poison(base, {root_para_id(base): POISON})
        assert POISON in part_text(package, "comments"), "fixture precondition: the parent is not poisoned"

        saved = reply_to_root(package)

        assert_word_readable_ids(saved, context="inherited parent paraId: ")
        entries = thread_of(saved)
        replies = {para_id: parent for para_id, parent in entries.items() if parent}
        assert len(replies) == 1, f"expected exactly one reply, got {entries}"
        parent = next(iter(replies.values()))
        assert parent in entries and not entries[parent], (
            f"the reply points at {parent}, which is not a thread root in {entries}. Word renders "
            "it as a second top-level comment: right author, right text, wrong place."
        )

    def test_the_repaired_root_keeps_the_replies_that_already_pointed_at_it(self):
        """
        The repair's own failure mode. Rewriting the root's paraId without
        rewriting the `w15:paraIdParent`s that referenced it turns one broken
        thread into N broken threads — strictly worse than doing nothing.
        """
        base = threaded_package(reply_count=2)
        package = poison(base, {root_para_id(base): POISON})

        saved = reply_to_root(package, text="Third reply.")

        entries = thread_of(saved)
        roots = [para_id for para_id, parent in entries.items() if not parent]
        parents = {parent for parent in entries.values() if parent}
        assert len(roots) == 1, f"the repair split the thread into {len(roots)} roots: {entries}"
        assert parents == set(roots), f"replies point at {parents}, thread root is {roots}: {entries}"
        assert len(entries) == 4, f"expected root + 3 replies, got {entries}"

    def test_the_repaired_para_id_is_identical_in_all_three_comment_parts(self):
        """
        Word consults comments.xml, commentsExtended AND commentsIds. A paraId
        repaired in one and left stale in another drops the comment out of the
        modern-comments path entirely — the same end state as not repairing it.
        """
        base = threaded_package(reply_count=1)
        package = poison(base, {root_para_id(base): POISON})

        saved = reply_to_root(package)

        for part in ("comments", "commentsExtended", "commentsIds"):
            text = part_text(saved, part)
            assert POISON not in text, f"{part} still carries the discarded paraId {POISON}"
        root = root_para_id(saved)
        assert f'w14:paraId="{root}"' in part_text(saved, "comments"), "root missing from comments.xml"
        assert f'w16cid:paraId="{root}"' in part_text(saved, "commentsIds"), "root missing from commentsIds"

    def test_the_repair_folds_rather_than_reinvents(self):
        """
        `D2AEAE20 -> 52AEAE20`: clear the top bit, which is what Word does to
        the value anyway. Pinned because it is the exact substitution that was
        verified in Word against the demo document, and because a deterministic
        repair keeps a re-run of the same document producing the same ids.
        """
        base = threaded_package(reply_count=0)
        package = poison(base, {root_para_id(base): POISON})

        saved = reply_to_root(package)

        assert root_para_id(saved) == POISON_FOLDED, (
            f"expected the root to fold to {POISON_FOLDED}, got {root_para_id(saved)}"
        )

    def test_inherited_out_of_range_rsids_are_repaired_too(self):
        """
        The demo document carried `w:rsidR/@w:rsidRDefault/@w:rsidP =
        AD3412F6` alongside the bad paraId. Word renumbers a PART, not an
        attribute, so leaving a bad rsid in comments.xml re-arms the same
        renumbering pass that de-threads the reply.
        """
        base = threaded_package(reply_count=0)
        package = poison(base, {root_para_id(base): POISON, **{r: "AD3412F6" for r in _rsids_of(base)}})
        assert "AD3412F6" in part_text(package, "comments"), "fixture precondition: no poisoned rsid"

        saved = reply_to_root(package)

        assert_word_readable_ids(saved, context="inherited rsid: ")
        assert "AD3412F6" not in part_text(saved, "comments")

    def test_the_repair_leaves_the_comment_body_author_and_date_untouched(self):
        """An id repair that edits the record it identifies is not a repair."""
        base = threaded_package(reply_count=0)
        package = poison(base, {root_para_id(base): POISON})

        saved = reply_to_root(package)

        comments = RedlineEngine(io.BytesIO(saved), author="x").comments_manager.extract_comments_data()
        root = next(c for c in comments.values() if c["text"] == "Root note.")
        original = next(
            c for c in RedlineEngine(io.BytesIO(package), author="x").comments_manager.extract_comments_data().values()
        )
        assert (root["author"], root["text"]) == (original["author"], original["text"])

    def test_a_package_whose_ids_are_already_legal_is_left_alone(self):
        """
        The repair must be a no-op on a healthy document. A pass that re-mints
        unconditionally would churn every paraId on every save and invalidate
        every `{#cell:<paraId>}` anchor the caller is holding — the exact
        damage it exists to prevent.
        """
        base = threaded_package(reply_count=1)
        before = set(para_ids_in(base))

        saved = reply_to_root(base)

        assert before <= set(para_ids_in(saved)), (
            f"the repair re-minted ids that were already legal: {before - set(para_ids_in(saved))}"
        )

    def test_a_reply_to_a_reply_still_flattens_onto_the_repaired_root(self):
        """
        Modern Word has no nesting: a reply to a reply points at the thread
        ROOT. That lookup runs through the poisoned value, so it has to see the
        repaired one.
        """
        base = threaded_package(reply_count=1)
        package = poison(base, {root_para_id(base): POISON})

        engine = RedlineEngine(io.BytesIO(package), author="Adeu AI")
        comments = engine.comments_manager.extract_comments_data()
        reply_id = list(comments)[-1]
        applied, skipped, _ = engine.apply_review_actions(
            [ReplyComment(target_id=f"Com:{reply_id}", text="Reply to the reply.")]
        )
        assert (applied, skipped) == (1, 0)
        saved = engine.save_to_stream().getvalue()

        entries = thread_of(saved)
        roots = [para_id for para_id, parent in entries.items() if not parent]
        assert len(roots) == 1, f"reply-to-reply created a second root: {entries}"
        assert all(parent == roots[0] for parent in entries.values() if parent), entries

    def test_the_engine_repairs_what_the_demo_document_actually_shipped(self):
        """
        End to end on the real shape: parent paraId AND its registrations in
        commentsExtended / commentsIds all poisoned together, which is how a
        fixture builder that rewrites ids leaves a document.
        """
        base = threaded_package(reply_count=0)
        package = poison(base, {root_para_id(base): POISON})
        assert [(a, v) for _p, a, v in find_out_of_range_long_hex_numbers(package)] == [
            ("w14:paraId", POISON),
            ("w15:paraId", POISON),
            ("w16cid:paraId", POISON),
        ], "fixture precondition: not the demo's shape"

        assert find_out_of_range_long_hex_numbers(reply_to_root(package)) == []


def _rsids_of(package: bytes):
    return set(re.findall(r'w:rsidR="([0-9A-Fa-f]{1,8})"', part_text(package, "comments")))


# ---------------------------------------------------------------------------
# The other two MUSTs the schema does not state
# ---------------------------------------------------------------------------


class TestParaIdUniqueness:
    """
    [MS-DOCX] 2.6.2.4: `w14:paraId` "specifies an identifier for a paragraph
    that is UNIQUE WITHIN THE DOCUMENT PART". Like the range rule, it is prose
    rather than schema, so nothing rejects a duplicate.

    It becomes load-bearing the moment ids are repaired rather than minted:
    folding clears the top bit, and `D2AEAE20` and `52AEAE20` fold to the SAME
    value. A repair that ignores uniqueness turns a dangling `paraIdParent`
    into an ambiguous one, which is not an improvement.
    """

    def test_a_freshly_written_thread_has_no_duplicate_para_ids(self):
        assert find_duplicate_para_ids(threaded_package(reply_count=3)) == []

    def test_repairing_never_collides_with_a_para_id_already_in_the_part(self):
        """
        The collision is constructed, not hoped for: the document already
        contains `52AEAE20`, which is exactly what `D2AEAE20` folds to.
        """
        engine = RedlineEngine(doc_stream(), author="Sarah Chen")
        engine.apply_edits(
            [
                ModifyText(target_text=TARGET, new_text=TARGET, comment="Root note."),
                ModifyText(target_text="production", new_text="production", comment="Second thread."),
            ]
        )
        base = engine.save_to_stream().getvalue()
        first, second = para_ids_in(base)[:2]
        package = poison(base, {first: POISON, second: POISON_FOLDED})
        assert POISON_FOLDED in part_text(package, "comments"), "fixture precondition: no collision to hit"

        saved = reply_to_root_of(package, POISON)

        assert find_duplicate_para_ids(saved) == [], (
            "the repair folded onto a paraId the part was already using; "
            "[MS-DOCX] requires paraId to be unique within the part"
        )
        assert_word_readable_ids(saved, context="collision repair: ")

    def test_the_duplicate_scanner_detects_a_collision(self):
        """Guards the guard: a scanner that never fires makes the above vacuous."""
        base = threaded_package(reply_count=1)
        ids = para_ids_in(base)
        collided = poison(base, {ids[1]: ids[0]})
        assert [(attr, value) for _part, attr, value in find_duplicate_para_ids(collided)] == [("w14:paraId", ids[0])]


def reply_to_root_of(package: bytes, para_id: str) -> bytes:
    """Reply to the comment whose paragraph carries `para_id`."""
    engine = RedlineEngine(io.BytesIO(package), author="Adeu AI")
    xml = part_text(package, "comments")
    match = re.search(
        r'<w:comment\b[^>]*\bw:id="(\d+)"(?:(?!</w:comment>).)*?w14:paraId="' + para_id + '"',
        xml,
        re.DOTALL,
    )
    assert match, f"no comment carries paraId {para_id}"
    applied, skipped, _ = engine.apply_review_actions(
        [ReplyComment(target_id=f"Com:{match.group(1)}", text="Addressed.")]
    )
    assert (applied, skipped) == (1, 0)
    return engine.save_to_stream().getvalue()


class TestTextIdAccompaniesParaId:
    """
    [MS-DOCX] 2.6.2.6: `w14:textId` carries the same range rule AND "any
    element having this attribute MUST also have the paraId attribute".

    Adeu writes `w14:textId` on every comment paragraph it creates, so the
    pairing is a real obligation, and it constrains the repair: stripping or
    renaming a paraId while leaving its textId behind produces an element that
    violates the spec even though every id on it is in range.
    """

    def test_every_text_id_travels_with_a_para_id(self):
        assert find_text_ids_without_para_id(threaded_package(reply_count=2)) == []

    def test_the_pairing_survives_repairing_an_inherited_para_id(self):
        base = threaded_package(reply_count=1)
        package = poison(base, {root_para_id(base): POISON})
        assert find_text_ids_without_para_id(reply_to_root(package)) == []

    def test_the_text_id_adeu_writes_is_in_range(self):
        """
        `w14:textId` is an ST_LongHexNumber like every other id here, and the
        package scanner already covers it. Stated separately because it is the
        one Adeu writes as a literal rather than from the generator.
        """
        for value in re.findall(r'w14:textId="([0-9A-Fa-f]{1,8})"', part_text(threaded_package(), "comments")):
            assert is_word_readable_long_hex_number(value), f"textId {value} is outside the legal range"

    def test_the_pairing_scanner_detects_a_lone_text_id(self):
        base = threaded_package(reply_count=0)
        orphaned = repack(base, lambda name, text: re.sub(r'\s*w14:paraId="[0-9A-Fa-f]{1,8}"', "", text, count=1))
        assert find_text_ids_without_para_id(orphaned), "the scanner missed a textId with no paraId"
